### ISSUE TITLE
i.headers is not iterable

### ISSUE THREAD

**Issue by mrehanabbasi** [ultram4rine/vscode-choosealicense#618] opened 2022-10-03 08:28 UTC
Extension Version: 0.9.0

When I try the _License: Choose license_ option in the command pallet, I get the following error in VSCode:
```
i.headers is not iterable
```
What seems to be the issue?

**Comment by mrehanabbasi** [comment] 2022-10-03 12:02
@ultram4rine So, what can be done?

**Comment by mrehanabbasi** [comment] 2022-10-03 12:15
I've even used a token but get the same error.

**Comment by adam248** [comment] 2022-10-10 03:34
I have the same error as well when I first tried to use this extension.
Wasn't even able to select a license for my first attempt.
Added a token as well ( blank permissions as I wasn't sure which one was needed for Github's API ) and assumed none.
`i.headers is not iterable` I believe is a type error due to the data returned from Github was not as expected by the extension.
Could you do a `try` and `expect` around i.headers and display `i`'s value so we can at least see the type and value of I to allow for easier debugging from the user-end...
Unless you already have a good idea of what is happening...
Perhaps the API data structure has changed?

Windows 10.0.19042
VSC  1.72.0

**Comment by ultram4rine** [comment] 2022-10-10 04:39
octokit/request.js#445 looks like the root cause.

**Comment by adam248** [comment] 2022-10-12 00:25
This might be related to these issues here:
https://github.com/RapidAPI/feedback/issues/72
https://github.com/microsoft/vscode/issues/163214

**Comment by adam248** [comment] 2022-10-12 00:28
When I disable the RapidAPI Client extension this extension now works.
I believe the RapidAPI Client is causing errors for all Github API related calls at the moment....
Please try and disable the RapidAPI Client extension to see if this works for you as well.

**Comment by ultram4rine** [comment] 2022-10-12 09:08
Hi @adam248, thanks for research. Now it is clear why I was unable to reproduce this error - I don't have RapidAPI extension. I confirm that with this extension the error appears.

As I can see the source of [RapidAPI Client](https://marketplace.visualstudio.com/items?itemName=RapidAPI.vscode-rapidapi-client) is closed, so we unable to see what actually happening.

**Comment by adam248** [comment] 2022-10-12 09:42
no worries @ultram4rine, I have disabled the extension for now and raised the issue with them.
I believe you should be able to close this issue once we have confirmed with @mrehanabbasi is using the RapidAPI Client extension as well.

**Comment by mrehanabbasi** [comment] 2022-10-12 09:50
I am using the RapidAPI Client extension and disabling it works for me as well.

**Comment by ultram4rine** [comment] 2022-10-12 10:29
Great. I then close this since the problem is not on our side.

**Closed by ultram4rine** 2022-10-12 10:29 UTC
